### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by DENightOne** [hardtechnology/EfergyMQTT#11]
Hi there, firstly, thanks for this makes my life alot easier (hopefully).   I have an e2 and will be hooking up a Wemos mini this weekend... I checked out the pic that you posted with the E2 and was wondering where you grounded the ESP...? as it does not show on the picture

**Comment by hardtechnology** [comment]
Hi, thanks for the question. Just use the solder pad where the negative battery terminal would have connected.

**Comment by DENightOne** [comment]
Cool.... Thanks again

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DENightOne** [comment]
Sorry to bug you...just 2 more questions:
1) How did you connect the dataout to the Wemos?  The pin input is 3.3v and I assume dataout is 5v...I tried putting a AMS1117 3.3 in between but maybe I am stupid but that does nothing. Resistor?

2) In the serial output I get this : 
{"MQTT":"CONNECTED"}
Efergy filter is in Blacklist Mode. TX in List: [NONE]
Running...
but I only see the following in MQTT:

/EfergyMQTT/Online True ?

IS that normal?

I changed the topic in the ino file to have a leadning / as all my topics have leading / .. would that break something? (PS....just changed it back to your code default...now in serial I see the sub message)

Thanks again

**Comment by hardtechnology** [comment]
Hi,
1. You can safely hook the ESP up directly to the Dataout pin, the receiver chip runs at about 2.7v, so no need for any converters.
2. It appears you are registering successfully with your MQTT server, but not receiving any data from an Efergy Transmitter. Check the data connection from the wemos to the efergy data out pin.

See how you go.

**Comment by DENightOne** [comment]
All set up and still getting nothing other then online true on mqtt:

Here is the serial output as I have enabled debug

{"RAW":[0,55,93,64,81,235,1,17]}LLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[511,72,71,72,73,72,72,73,69,73,72,143,141,67,139,136,132,63,137,64,136,134,134,61,132,63,136,64,65,66,67,68,65,69,141,68,68,139,137,136,132,63,136,63,135,134,134,62,60,65,67,68,69,69,70,69,137,142,66,67,68,69,70,71,67,137,132,66]}
{"RAW":[0,55,93,64,79,92,1,128]}LLLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[510,71,71,71,72,71,72,72,69,72,72,143,141,66,139,136,132,63,136,63,135,134,134,61,131,62,136,64,65,66,67,68,65,68,141,66,140,67,68,68,136,140,136,136,62,136,63,135,128,63,65,66,67,68,69,68,137,67,68,68,140,67,68,68,137,32,59,50]}
{"RAW":[0,55,93,64,81,235,1,17]}LLLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[510,71,71,72,73,72,73,73,69,73,71,143,141,67,138,137,132,64,137,64,136,134,134,61,132,63,136,64,65,66,67,68,65,69,141,67,140,67,68,68,136,140,135,135,62,135,62,135,130,62,65,66,67,68,69,69,137,68,69,69,141,67,68,68,136,24,29,46]}
{"RAW":[0,55,93,64,81,235,1,17]}LLLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[510,71,71,71,72,72,72,72,68,72,72,142,140,67,139,137,132,63,137,63,136,135,135,62,131,62,135,63,65,66,67,68,65,69,141,67,140,67,67,69,65,144,67,139,66,68,68,139,135,66,67,68,69,69,70,69,138,140,138,64,65,139,65,66,64,54,48,67]}
{"RAW":[0,55,93,64,80,163,1,200]}LLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[510,70,71,71,72,71,72,71,69,72,72,143,141,66,139,136,132,63,137,63,135,134,134,61,131,62,136,64,65,66,67,68,65,69,141,67,140,67,68,68,136,140,136,135,62,137,62,136,131,63,65,66,67,68,69,68,137,68,68,68,141,67,68,68,137,42,41,25]}
{"RAW":[0,55,93,64,81,235,1,17]}LLLLLLLLLLLLLLL
SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbECS{"BituSec":[510,71,71,72,71,72,72,72,68,73,71,142,141,67,139,137,133,63,137,64,136,135,134,61,131,62,136,63,64,66,67,68,65,68,141,67,140,66,67,68,136,139,135,135,62,136,63,135,130,63,64,66,67,67,68,68,137,68,69,69,141,67,68,68,136,29,59,27]}

How do I find the TX number to add ?

Thanks again for the help

Update: I notived that the string ended in CS....so found the checksumok check....I hacked the Check to report true and now it works great??? any idea why that would be?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DENightOne** [comment]
Hi there, its me again :).... This has been working fine since yesterday,,, graphing nicely in emoncms..when I checked the MQTT server this morning there are thousands of entries for different TX names:

EfergyMQTT/1036/Interval1
EfergyMQTT/1036/Online1
EfergyMQTT/1036/Type1
EfergyMQTT/1036/Voltage1
EfergyMQTT/1036/Watt1
EfergyMQTT/10368/BattOK1
EfergyMQTT/10368/Interval1
EfergyMQTT/10368/Online1
EfergyMQTT/10368/Type1
EfergyMQTT/10368/Voltage1
EfergyMQTT/10368/Watt1
EfergyMQTT/10388/BattOK1
EfergyMQTT/10388/Online1
EfergyMQTT/10388/Type1
EfergyMQTT/10388/Voltage1
EfergyMQTT/104/Online1
EfergyMQTT/104/Type1
EfergyMQTT/104/Voltage1
EfergyMQTT/1040/BattOK1
EfergyMQTT/1040/Interval1
EfergyMQTT/1040/Online1
EfergyMQTT/1040/Type1
EfergyMQTT/1040/Voltage1

This is a small sample there are thousands...is there a way of stopping this?

**Comment by hardtechnology** [comment]
Hi, Sorry for the delay. You can use the blacklist/whitelist feature to only accept your own ID number. From your previous debug information and above it appears there is a lot of interference on the frequency band the Efergy is using. I have seen this when the transmitter and receiver are either too close, or too far away. If you aren't getting any valid information, your Efergy may be running a different protocol, as there are a couple of different standards.
