### ISSUE TITLE
My board  seems something different

### ISSUE THREAD

**Issue by jmartnav** [hardtechnology/EfergyMQTT#15]
Hi, 
I´m very excited about the pissibility of giving MQTT capabilities to my efergy E2 and integrate it in Home Assistant. I have compiled de firmware for a D1 mini module without issues (incredible, first time¡¡¡¡). 

My board seems something different from that you present in the pictures, so I would like your opinion about if the connections suggested in the attached picture  are  equivalents.

About powering , is it possible to feed D1 module from the board power plug contacts directly?

And the last question, should I see something in the arduino monitor serie if I feed the D1 module throught USB port and then link DATA OUT with D0 pin ?

Thank you very much ¡¡¡¡

I look forward to your comments

![image](https://user-images.githubusercontent.com/52754464/151762229-9c1b30ba-e608-4eac-a510-c6d7aede7563.png)

**Comment by steven-geo** [comment]
Your board looks very similar to this one: https://github.com/hardtechnology/EfergyMQTT/blob/main/E2.jpg probably just a minor revision.
you can power an ESP from this board - see the E2.jpog linked above to pickup the 5V from, then you can just plug the USB plug for power to the receiver, and place the ESP8266/WemosD1 into the battery compartment.

Data out will only show information with Debug turned on and receiving information. Once other person didn't receive any data, so please check it out, and timings may need to be different as the code is only tested on a 433MHz system. 
I would recommend changing to the new repo, as I don't support this code any more. The new version has much better debugging built in. 
see: https://github.com/hardtechnology/efergy_v2
This one you can write your own integration to suit your own needs too, as it is built as a library.

**Comment by jmartnav** [comment]
Hi, 

thank you very much for your response.
I should like to use the new versión of the library but I don´t know very much about arduino IDE and coding. I can compile scripts, upload them, look for needed libraries and things like that, so I don´t know de syntax for cofing.
If you are so kind, I´m near from succes and I only need response to one question. I´m getting records through serial port:


{"TX":1489,"W":388}
{"TX":1489,"W":386}
{"TX":1489,"W":399}
{"TX":1489,"W":390}
{"TX":1489,"W":388}
....

and the mqtt broker is answering to the topics to control the module, but, what topic should I subscribe to get de the measurements in a MQTT client?

Thank you very much.

**Comment by steven-geo** [comment]
Hi, Just had a look at the code. This is configured as part of the Wifi configuration. So when you try to connect it to Wifi, it will ask you for the topic/user/pass to use for MQTT connections. See here: https://github.com/hardtechnology/EfergyMQTT#configuration

**Comment by jmartnav** [comment]
Hi Steven,
thank you very much. You are very kind. I have everything working very, very well. I configured mi MQTT App with topic EfergyMQTT/# and I got the topic I needed. Only one question more: Could I get the measurements of another  Efergy transmiter if I buy another one?
Thank you very much.

**Comment by steven-geo** [comment]
Hi, Yes. I think I had 3 or 4 working on this code, and it theoretically will work with 6-10 sensors. So no problem there.
